version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    container_name: jenkins
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    group_add:
      - 125

volumes:
  jenkins_home:

networks:
  jenkins: